### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by MrManny** [AlexDM0/keycharm#6]
Greetings,

I was wondering if there are any plans to release TypeScript definition files.
I am working on a project that exclusively uses TypeScript and keycharm was pulled in as a dependency of one of my dependencies. This is causing my TypeScript compiler to [be a little bit complainy](https://github.com/visjs/vis-network/issues/164) about keycharm not having any typings.

While it's trivial to work around my issue, it might actually also be interesting to just add TypeScript definitions to this project. If you are short on time, I can give it a shot over the course of the next weeks and open a PR afterwards.

Let me know your thoughts and plans on this subject matter.

Kind regards,
M.

**Comment by AlexDM0** [comment]
Hi there! 

If you're willing to make a PR with typings I'll gladly add it to the module!

Cheers

**Comment by MrManny** [comment]
Hi Alex,

thank you for the swift response. I will try to have a look at it in the coming weeks if I can and nobody else gets it done first. :)

M.

**Comment by cloakedninjas** [comment]
Given that the definition are on master, could someone publish this to npm?

**Comment by AlexDM0** [comment]
I have pushed 0.3.1 to npm
