### ISSUE TITLE
export also as ESM module

### ISSUE THREAD

**Issue by mojoaxel** [AlexDM0/keycharm#9]
We get the following waning in an Angular project using keychartm (for vis-timeline):

```
WARNING in node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js depends on 'keycharm'.
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

It would be helpfull to also export a ESM module.
I'll try to look into this issue within the next weeks, but if somebody wants to help, please feel free to do so ;-)

**Comment by mojoaxel** [comment]
@AlexDM0 Maybe you can label this issue with `Hacktoberfest`!?
(see https://hacktoberfest.digitalocean.com/#maintainers)

**Comment by AlexDM0** [comment]
@mojoaxel Sure, it's labeled. Let me know what you find!

**Comment by mojoaxel** [comment]
@AlexDM0 Sorry to bother you again but to be part of hacktoberfest the project needs a "topic" `hacktoberfest` to the project. ;-)

> Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
> Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by AlexDM0** [comment]
@mojoaxel I've added you as a contributor. I havent looked too much into hacktoberfest, so if you think this would be a fun candidate, I'll leave it up to you to add it :)

**Comment by mojoaxel** [comment]
> I've added you as a contributor.

Thanks, but with the current rights I cannot add topics or labels :wink: but that's ok...

**Comment by AlexDM0** [comment]
I see, I added the topic now. I didn't know those existed to be honest :)
